### ISSUE TITLE
Cant click on smilator

### ISSUE THREAD

**Issue by caglarsarikaya** [brizzinck/Woodoku#2]
I installed the app, opend on unity and started but can't click the blocks on the game start screen.
Game start button and other buttons are working but on game screen, every buttons works except block buttons ont the bottom of screen 3 of block button

**Comment by brizzinck** [comment]
Hi. I don’t know what the problem is, maybe you have the wrong version of the Unity?

**Comment by brizzinck** [comment]
> I installed the app, opend on unity and started but can't click the blocks on the game start screen. Game start button and other buttons are working but on game screen, every buttons works except block buttons ont the bottom of screen 3 of block button

Hi. I don’t know what the problem is, maybe you have the wrong version of the Unity?

**Comment by caglarsarikaya** [comment]
yes you right, I solve it, there many versions of unity, I wasn't know that
